### ISSUE TITLE
Set up Polis, Columbin Republic, etc reforms

### ISSUE THREAD

**Issue by Firesoul7** [Firesoul7/Mars_Universalis#5]
This is necessary before I personally would consider us ready for the next release

**Comment by Firesoul7** [comment]
I think that 'etc' just describes Young Colony. EP, there were some plans in place for the Young Colony reform tree, what were they? Thank you

**Comment by SevyRide** [comment]
Is there a list of Olympian countries?  Because I have to edit the default government of every Olympian nation in the history files and I don't know which ones those are.

**Comment by Firesoul7** [comment]
You don't, that bit is already done. The Columbin Republic is also implemented in that way, it's just that since the reform itself hasn't had anything done for it they choose randomly ingame. As soon as the reform is implemented along with its localisation the appropriate nations will get the appropriate governments

**Comment by Firesoul7** [comment]
government = republic
add_government_reform = polis
technology_group = olympian
primary_culture = thireftis
religion = olympic
capital = 1219
religious_school = Athena

Here's an example file, the reform is already there in the history files, it just doesn't work ingame, which leads them to pick an available initial reform at random

**Comment by SevyRide** [comment]
Ah, that's why, I called it polis_reform, since that's how the other ones looked.  I should change mine, right?

**Comment by Firesoul7** [comment]
It would be easier, yes. Thank you

**Comment by Firesoul7** [comment]
There's a sort of unofficial convention that standard reforms available to all use _reform at the end where special ones only for particular groups don't

**Comment by Firesoul7** [comment]
Eg feudalism_reform vs daimyo

**Comment by SevyRide** [comment]
ah, ok.

**Comment by SevyRide** [comment]
Polis and Columbine should be done now. (unless I forgot something/there are bugs.  which is likely :/ )

**Comment by Firesoul7** [comment]
I've checked it, there was a minor 'bug' in the Columbin Republic which made it so that it was assigned to the wrong culture for custom nations, but otherwise both were perfect.

EP has promised to send us an Excel file with details on the Young Colony thing, until then if you want something to work on, I've noticed that you're good at events, which is a rare skill, so maybe you could work on some of the events that I have planned for the Vietnamese.

Specifically: these events would be tied to government reforms (so heavy use of has_reform = ), and would basically show the effects of the decisions made by yourself and other states. Examples, if you have the reform che_de_tai_phiet_v_reform and the reform bureaucrat_v_reform you'll occasionally get an event talking about how the merchants are neglecting the interior of the country is favour of the ports. This will have two options, one of which is to attempt to rein the merchants in, for a hit to stability and a cash cost, the other option is basically to accept it, which will cause an increase to revolt risk in any non-coastal provinces. If you have the dang_cap_v_reform reform, you'll sometimes get events talking about talented commoners, giving you a choice between raising them up and keeping them in poverty, with a legitimacy hit but the gaining of a good advisor for the first, no effect for the second. The Arrival Reaction reforms would all have associated events. offense_reaction_v_reform will sometimes make your neighbours hate you, defense_reaction_v_reform will hurt your trade power and also other people's trade power in certain areas, and cause minor relation penalties, where diplomatic_reaction_v_reform will have nice effects giving you relations boosts with your neighbours (partly because diplomatic_reaction_v_reform is the weakest of the three otherwise). I have a bunch of other ideas for them and I'm sure that you can come up with some good ideas too

**Comment by Firesoul7** [comment]
[MU_Government_Reforms.xlsx](https://github.com/Firesoul7/Mars_Universalis/files/2447546/MU_Government_Reforms.xlsx)
Here's the tree for the Young Colony reforms. There's a partial tree for the Polis too, as an alternative to having them be a regular republic, but personally I don't think that that's urgent

**Comment by SevyRide** [comment]
I do think Polis should be it's own government form (not just a merchant reform) because it makes more sense thematically.

**Comment by Firesoul7** [comment]
Sure, I'm just saying that the Young Colony one is a priority, for the simple reason that they currently have nothing. If you can do that and then afterwards you want to make Polis into a full reform tree, then absolutely, please do it

**Comment by SevyRide** [comment]
Ok, I just looked at the Young Colonies reforms, and I see a problem: the "explore adjacent to colonized" doesn't work in any of the scopes government has access to.  I was trying to get this to work with Columbine and couldn't.  That modifier only works within ideas, which is why I made a new idea set for Columbine.  We'll have to find a workaround.  A few possibilities that come to mind are:
1) Make a Young Colony idea set that has "explore adjacent to colonized" in it's traditions
2) For each Young Colony, make an alternate set of ideas with "explore adjacent to colonized" in it's 
         traditions, and then switch idea sets to the actual ideas later in the game.
3) Make a hidden (or maybe not hidden) event that auto-explores neighboring provinces periodically
4) Make a decision ("send out explorers!" or so-such) that costs something and explores neighboring 
         provinces (possibly limited to how many it finds or something)
5) Have them start at tech 5 with exploration ideas and quest for the new world unlocked (pretty drastic)

**Comment by SevyRide** [comment]
Let me run a few tests, I'll get back to you in a bit.

**Comment by SevyRide** [comment]
So it's definitely possible to make a decision that'll uncover provinces.  Have the rough thing down.  Now it's just finding the right syntax of every_/any_/all_/random_ that sets it up so that it's only visible if there are provinces to discover and it only discovers provinces that need to be discovered.  If you don't mind, I'll work on this tomorrow (I'm going to bed now)

**Comment by Firesoul7** [comment]
I'd say that's already good enough in theory, it just relies on the player being sensible and not throwing money away

**Comment by Firesoul7** [comment]
Hmm... I just had an idea, would the explore adjacent to colonised thing work in an event modifier?

**Comment by SevyRide** [comment]
I don't think so, when the Wiki specifically states that modifiers like that only work in ideas :/

**Comment by Firesoul7** [comment]
Unfortunate((

**Comment by Firesoul7** [comment]
Notes: There are plans to turn Polis into a full fledged reform tree. The Columbin Republic is done. Young Colony is in progress

**Comment by SevyRide** [comment]
Regarding the "explore" decision, it might be easier to tie a startup-event to the young_colony government that gives them a conquistador or explores the neighboring provinces and their capital state for them (the second would be my preferred route, since we're really only tiding them over until they can get exploration ideas if I'm getting this right, and states in MU are bigger than in vanilla on average iirc).  I'm having trouble getting the trigger effects to update in a decision that can be taken multiple times (so I can't get the decision to check newly acquired provinces' neighbors to see if they aren't discovered).

**Comment by Firesoul7** [comment]
Regarding the Young Colony thing, it's possible that the reason it's using the legacy thing is because all legacies should appear before the mechanic in files, I'll quickly fix it for you once I've written this up. As to why the countries that should be young colonies aren't, it's because history still hasn't been done for most of them, that's another fix that I can do

**Comment by Firesoul7** [comment]
Moving the legacy thing didn't seem to work, but as you said it's not that important if it still works. Regarding the localisation, do you want to do it or should I? As to the decision/event, what you do is up to you, do whatever you feel is best

**Comment by Firesoul7** [comment]
Having implemented the Young Colony localisation, I consider this done enough for release

**Comment by Firesoul7** [comment]
Ok, so I'm pretty sure that the only thing left to finish this issue is to redo the Polis tree, and I think there was an actual plan as to how to do that somewhere

**Comment by Firesoul7** [comment]
The specs of this have changed so completely that this needs to be closed and maybe another similar issue opened for doing the Olympic government tree
